version: "3.7"

services:
  dragonloopapi:
    image: ${DOCKER_REGISTRY-}dragonloopapi${TAG-}
    ports:
      - 5000:80
    build:
      target: dev
      context: .
      dockerfile: DragonLoopAPI/Dockerfile
    depends_on:
      - db

  dragonloopweb:
    image: ${DOCKER_REGISTRY-}dragonloopweb${TAG-}
    ports:
      - 8000:80
    build:
      target: dev
      context: .
      dockerfile: DragonLoopWeb/Dockerfile

  db:
    image: postgres:12-alpine
    volumes:
      - db-data:/var/lib/postgresql/data

  nginx:
    image: ${DOCKER_REGISTRY-}nginx${TAG-}
    build:
      context: ./nginx
    ports:
      - 80:80
    restart: always

volumes:
  db-data:
    driver: local
