version: "3.7"

services:
  dragonloopapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - "./DragonLoopApi:/src/DragonLoopApi"

  dragonloopweb:
    volumes:
      - "./DragonLoopWeb:/src/DragonLoopWeb"

  db:
    ports:
      - "5432:5432"
