version: "3.7"

services:
  dragonloopapi:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      PG_CONNECTION_STRING: "User ID=postgres;Host=db;Port=5432;Database=postgres;"
    volumes:
      - "./DragonLoopApi:/src/DragonLoopApi"
    build:
      target: ${DOCKER_TARGET}
      context: .
      dockerfile: DragonLoopAPI/Dockerfile

  dragonloopweb:
    volumes:
      - "./DragonLoopWeb:/src/DragonLoopWeb"
    build:
      target: ${DOCKER_TARGET}
      context: .
      dockerfile: DragonLoopWeb/Dockerfile

  nginx:
    build:
      context: ./nginx
