version: "3.7"

services:
  dragonloopapi:
    image: docker.pkg.github.com/dragon-loop/dragonloop/dragonloopapi:${TAG}
    ports:
      - 5000:80
    build:
      target: ${DOCKER_TARGET}
      context: .
      dockerfile: DragonLoopAPI/Dockerfile
    depends_on:
      - db

  dragonloopweb:
    image: docker.pkg.github.com/dragon-loop/dragonloop/dragonloopweb:${TAG}
    ports:
      - 8000:80
    build:
      target: ${DOCKER_TARGET}
      context: .
      dockerfile: DragonLoopWeb/Dockerfile

  db:
    image: postgres:12-alpine
    volumes:
      - db-data:/var/lib/postgresql/data

  nginx:
    image: docker.pkg.github.com/dragon-loop/dragonloop/nginx:${TAG}
    build:
      context: ./nginx
    ports:
      - 80:80
    restart: always

volumes:
  db-data:
    driver: local
