version: "3.7"

services:
  dragonloopapi:
    image: docker.pkg.github.com/dragon-loop/dragonloop/dragonloopapi:${TAG}
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      PG_CONNECTION_STRING: "User ID=admin;Host=db;Port=5432;Database=postgres;Password=${POSTGRES_PASSWORD};"
    ports:
      - 5000:80
    depends_on:
      - db

  dragonloopweb:
    image: docker.pkg.github.com/dragon-loop/dragonloop/dragonloopweb:${TAG}
    ports:
      - 8000:80

  db:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  nginx:
    image: docker.pkg.github.com/dragon-loop/dragonloop/nginx:${TAG}
    ports:
      - 80:80
    restart: always

volumes:
  db-data:
    driver: local
