version: "3.7"

services:
  dragonloopapi:
    image: ${DOCKER_REGISTRY-}dragonloopapi
    build:
      context: .
      dockerfile: ./Dockerfile.api

  dragonloopweb:
    image: ${DOCKER_REGISTRY-}dragonloopweb
    build:
      context: .
      dockerfile: DragonLoopWeb/Dockerfile

  db:
    image: postgres:12-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:
    driver: local
