version: '3.7'

services:
  dragonloopapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro