name: Deploy to staging

on: 
  push:
    branches: 
      - develop
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master

    - name: 'Docker login'
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com/dragon-loop/dragonloop/
        username: ${{ secrets.GITHUB_DOCKER_USERNAME }}
        password: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}

    - name: 'Docker Build'
      run: |
        docker-compose -f docker-compose.yml -f docker-compose.prod.yml build
        docker-compose -f docker-compose.yml -f docker-compose.prod.yml push
