name: Deploy to staging

on: 
  pull_request:
    branches: 
      - develop

jobs:
  build:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
  
    steps:
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
  
    - name: 'Login, build and push to registry'
      env:
        DOCKER_USERNAME:  ${{ secrets.GITHUB_DOCKER_USERNAME }}
        DOCKER_REGISTRY: docker.pkg.github.com/dragon-loop/dragonloop/
        GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}
        TAG: staging
    - run: |
        cd ./DragonLoop
        docker login docker.pkg.github.com -u "${DOCKER_USERNAME}" -p "${GITHUB_PACKAGE_REGISTRY_TOKEN}"
        docker-compose build
        docker-compose push
        
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/webapps-container-deploy@v1
      with:
        app-name: dragonloops
        creds: ${{ secrets.azureWebAppPublishProfile }}
      
